apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: grafana
    labels:
      app: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: default
  labels:
    app: grafana
spec:
  accessModes:
  - ReadWriteOnce
  # storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: img-grafana
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - livenessprobe.sh
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: grafana-pv
            mountPath: /root/grafana/data
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc