apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: phpmyadmin
  name: phpmyadmin
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: phpmyadmin
  template: 
    metadata: 
      labels: 
        app: phpmyadmin
    spec: 
      containers: 
        - 
          image: pma
          imagePullPolicy: Never
          name: phpmyadmin
          env: 
          - 
            name: PMA_HOST
            value: mysql
          - 
            name: PMA_PORT
            value: "3306"
          ports: 
          - 
            containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: phpmyadmin
spec:
    selector:
        app: phpmyadmin
    type: LoadBalancer
    ports:
        -   name: http
            protocol: TCP
            port: 5000
            targetPort: 5000
    # loadBalancerIP: 172.17.0.4
