apiVersion: v1
kind: Service
metadata:
    name: ftps
    labels:
      app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: img-ftps
        imagePullPolicy: Never

        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        # volumeMounts:
        #   - name: ftps-pv
        #     mountPath: ftp
      volumes:
        - name: ftps-pv
          hostPath:
            path: ftp
            type: Directory