
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: nginx
  name: nginx
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
        - 
          image: nginx
          imagePullPolicy: Never
          name: nginx
          ports: 
          - containerPort: 80
          - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  annotations:
        metallb.universe.tf/allow-shared-ip: shared
        metallb.universe.tf/address-pool: ip-pools
  name: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
