apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  serviceName: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wp-ctn2
        imagePullPolicy: Never
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 5050
        #     httpHeaders:
        #     - name: Custom-Header
        #       value: Awesome
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        env:
          - name: WP_USER_PASS
            valueFrom:
              secretKeyRef:
                name: global-secret
                key: wp_user_password
        ports:
        - containerPort: 5050

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wp-deployment
#   labels:
#     app: wp-ctn2
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: wp-ctn2
#   template:
#     metadata:
#       labels:
#         app: wp-ctn2
#     spec:
#       containers:
#       - name: wp-ctn2
#         image: wp-ctn2
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#     name: svc-test
# spec:
#     selector:
#         app: wp-ctn2
#     type: LoadBalancer
#     ports:
#         -   name: http
#             protocol: TCP
#             port: 80
#             targetPort: 80