apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wp-ctn2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-ctn2
  template:
    metadata:
      labels:
        app: wp-ctn2
    spec:
      containers:
      - name: wp-ctn2
        image: wp-ctn2
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: svc-test
spec:
    selector:
        app: wp-ctn2
    type: LoadBalancer
    ports:
        -   name: http
            protocol: TCP
            port: 80
            targetPort: 80