# apiVersion: v1
# kind: Service
# metadata:
#     name: wp-mysql
#     labels: 
#         app: wordpress
# spec:
#   selector:
#     app: wordpress
#     tier: mysql
#   type: ClusterIP
#   ports:
#   - port: 3306
#     targetPort: 3306
# apiVersion: v1
# kind: Service
# metadata:
#     name: wordpress-mysql
# #   labels:
# #     app: wordpress
# spec:
#   ports:
#     - port: 3306
#   selector:
#     app: wordpress
#     tier: mysql
#   clusterIP: None

# apiVersion: apps/v1
# kind: deployment
# metadata:
#   name: wp-mysql
# spec:
#   selector:
#     matchLabels:
#       app: wordpress
#       tier: mysql
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: wordpress
#         tier: mysql
#     spec:
#       containers:
#       - name: mysql
#         image: mysql-ctn
#         imagePullPolicy: Never
#         # livenessProbe:
#         #   exec:
#         #     command:
#         #     - /bin/ash
#         #     - /root/livenessprobe.sh
#         #   initialDelaySeconds: 5
#         #   periodSeconds: 5
#         env:
#         - name: MYSQL_ROOT_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: root-pass
#               key: password
#         - name: MYSQL_DATABASE
#             value: mysql
#             - name: MYSQL_USER
#             value: mysql
#             - name: MYSQL_PASSWORD
#                 valueFrom:
#                 secretKeyRef:
#                     name: mysql-pass
#                     key: password
#           volumeMounts:
#           - name: mysql-pv
#             mountPath: /var/lib/mysql
#         ports:
#         - containerPort: 3306
#       volumes:
#         - name: mysql-pv
#           persistentVolumeClaim:
#             claimName: mysql-pvc

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: root-pass
              key: password

        - name: MYSQL_DATABASE
          value: mysql

        - name: MYSQL_USER
          value: mysql

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password

        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      nodeSelector:
        storage: local
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim