# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pvc
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: svc-wordpress
# spec:
#   selector:
#     app: wordpress
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 80
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wordpress
#   labels:
#     app: wordpress
# spec:
#   selector:
#     matchLabels:
#       app: wordpress
#   replicas: 1
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: wordpress
#     spec:
#       containers:
#       - image: wp-ctn2
#         name: wordpress
#         imagePullPolicy: Never

#         env:
#         - name: WORDPRESS_DB_HOST
#           value: wordpress-mysql

#         - name: WORDPRESS_DB_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-pass
#               key: password

#         - name: WORDPRESS_DB_USER
#           value: mysql

#         - name: WORDPRESS_DB_NAME
#           value: mysql

#         ports:
#         - containerPort: 5050
#           name: wordpress
#         volumeMounts:
#         - name: wp-pv
#           mountPath: /var/www/html
#       nodeSelector:
#         storage: local
#       volumes:
#       - name: wp-pv
#         persistentVolumeClaim:
#           claimName: wp-pvc



# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: wordpress
# spec:
#   selector:
#     matchLabels:
#       app: wordpress
#   serviceName: wordpress
#   template:
#     metadata:
#       labels:
#         app: wordpress
#     spec:
#       containers:
#       - name: wordpress
#         image: wp-ctn2
#         imagePullPolicy: Never
#         # livenessProbe:
#         #   httpGet:
#         #     path: /
#         #     port: 5050
#         #     httpHeaders:
#         #     - name: Custom-Header
#         #       value: Awesome
#         #   initialDelaySeconds: 3
#         #   periodSeconds: 3
#         env:
#           - name: WP_USER_PASS
#             valueFrom:
#               secretKeyRef:
#                 name: mysql-pass
#                 key: password
#         ports:
#         - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: wordpress
  name: wordpress
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: wordpress
  template: 
    metadata: 
      labels: 
        app: wordpress
    spec: 
      containers: 
        - 
          image: wp-ctn2
          imagePullPolicy: Never
          name: wordpress
          livenessProbe:
            exec:
              command:
              - /bin/ash
              - livenessprobe.sh
            initialDelaySeconds: 10
            periodSeconds: 10
          env: 
          - 
            name: DB_NAME
            value: wordppress
          - 
            name: DB_USER
            value: admin
          - 
            name: DB_PASSWORD
            value: admin
          - 
            name: DB_HOST
            value: mysql
          ports: 
          - 
            containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
      metallb.universe.tf/address-pool: ip-pools
    name: wordpress
spec:
    selector:
        app: wordpress
    type: LoadBalancer
    ports:
        -   name: http
            protocol: TCP
            port: 5050
            targetPort: 5050
    # loadBalancerIP: 172.17.0.4