apiVersion: v1
kind: Service
metadata:
    name: telegraf
    labels:
      app: telegraf
spec:
  selector:
    app: telegraf
  type: ClusterIP
  ports:
  - port: 8125
    targetPort: 8125
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: influxdb-pvc
#   namespace: default
#   labels:
#     app: influxdb
# spec:
#   accessModes:
#   - ReadWriteOnce
#   # storageClassName: local-storage
#   resources:
#     requests:
#       storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: img-telegraf
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - livenessprobe.sh
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 8125
        volumeMounts:
          - name: telegraf-endpoint
            mountPath: "/var/run/docker.sock"
      volumes:
        - name: telegraf-endpoint
          hostPath:
            path: /var/run/docker.sock