apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - name: ftps-20
    port: 20
    targetPort: 20
  - name: ftps-21
    port: 21
    targetPort: 21
  - name: ftps-21000
    port: 21000
    targetPort: 21000
  - name: ftps-21001
    port: 21001
    targetPort: 21001
  - name: ftps-21002
    port: 21002
    targetPort: 21002
  - name: ftps-21003
    port: 21003
    targetPort: 21003
  - name: ftps-21004
    port: 21004
    targetPort: 21004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: img-ftps
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - livenessprobe.sh
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        # volumeMounts:
        #   - name: ftps-pv
        #     mountPath: /var/lib/mysql
      # volumes:
      #   - name: ftps-pv
      #     hostPath:
      #       path: /home/user42/Bureau/42/ft_services_git/ftps/ftp
      #       type: Directory